
title: Jaejun Ko
email: jaejun.ko@snu.ac.kr
description: >-
github_username: kojaejun
minimal_mistakes_skin: default
locale: "en-US"
search: false

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
permalink: /:categories/:title/

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Jaejun Ko"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Master's student studying Cryptography in **[SNUCP](https://crypto.snu.ac.kr)**."
  location : "Seoul National University"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ko-jaejun"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jaejunko"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ash.6__"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ko-jaejun"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jaejunko"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ash.6__"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
